openapi: 3.0.3
info:
  title: DenseEdia
  version: '0.1'
  description: The API of DenseEdia
  contact:
    email: fabien.sabre@gmail.com
    name: Fabien Sabre
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /edia:
    get:
      summary: Retrieve a list of all Edia
      description: ''
      operationId: 'get_edia'
      responses:
        '200':
          description: Return the list of all Edia
      tags:
        - Edia
  '/edia/{edium_id}':
    get:
      summary: Retrieve one Edium
      description: ''
      operationId: 'get_one_edium'
      responses:
        '200':
          description: Return one Edium
        '404':
          description: No Edium found with the provided ID
      tags:
        - Edia
      parameters:
        - name: edium_id
          in: path
          description: ID of the Edium to return
          required: true
          schema:
            type: integer
            format: int64
  '/edia/{edium_id}/elements':
    get:
      summary: Retrieve the Elements of an Edium
      description: ''
      operationId: 'get_edium_elements'
      responses:
        '200':
          description: Return a list of Elements
        '404':
          description: No Edium found with the provided ID
      tags:
        - Elements
      parameters:
        - name: edium_id
          in: path
          description: ID of the Edium to look for
          required: true
          schema:
            type: integer
            format: int64
  /elements:
    get:
      summary: Retrive a list of all Elements
      description: ''
      operationId: 'get_elements'
      responses:
        '200':
          description: Return the list of all Elements
      tags:
        - Elements
  /elements/{element_id}:
    get:
      summary: Retrieve one Element
      description: ''
      operationId: 'get_one_element'
      responses:
        '200':
          description: Return one Element
        '404':
          description: No Element found with the provided ID
      tags:
        - Elements
      parameters:
        - name: element_id
          in: path
          description: ID of the Element to return
          required: true
          schema:
            type: integer
            format: int64
  /links:
    get:
      summary: Retrieve a list of all Links
      description: ''
      operationId: 'get_links'
      responses:
        '200':
          description: Return the list of all Links
      tags:
        - Links
  /links/{link_id}:
    get:
      summary: Retrieve one Link
      description: ''
      operationId: 'get_one_link'
      responses:
        '200':
          description: Return one Link
        '404':
          description: No Link found with the provided ID
      tags:
          - Links
      parameters:
        - name: link_id
          in: path
          description: ID of the Link to return
          required: true
          schema:
            type: integer
            format: int64
tags:
  - name: Edia
    description: Operations related to Edia
  - name: Elements
    description: Operations related to Elements
  - name: Links
    description: Operations related to Links
servers:
  - url: 'http://localhost:59130'
    description: The Flask API server
    variables: {}
